In [1]:
import numpy as np

### 2-5 取最大最小值
- amax()
- amin()

#### 2-5-1 np.amax()
- np.amax(a, axis=None, out=None, keepdims=False)

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
# 回傳最大值
np.amax(a)

6

In [4]:
b = a.reshape(-1, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 回傳最大的那 row
np.amax(b, axis=0)

array([4, 5, 6])

In [6]:
# 回傳最大的那 col
np.amax(b, axis=1)

array([3, 6])

In [7]:
# 保留維度
np.amax(b, axis=1, keepdims=True)

array([[3],
       [6]])

#### 2-5-2 np.max()
- method

In [8]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[15, 14, 26, 27, 15],
        [12, 24, 25, 14, 12],
        [24,  2, 21,  4, 10]],

       [[16, 11,  1, 21,  3],
        [ 0, 10, 22, 28,  5],
        [19,  0,  9,  4, 14]]])

In [9]:
# 比較兩個陣列, 提出最大值
b.max(axis=0)

array([[16, 14, 26, 27, 15],
       [12, 24, 25, 28, 12],
       [24,  2, 21,  4, 14]])

In [10]:
# 兩個陣列每col最大值
b.max(axis=1)

array([[24, 24, 26, 27, 15],
       [19, 11, 22, 28, 14]])

In [13]:
# 兩個陣列每row最大值
b.max(axis=2)

array([[27, 25, 24],
       [21, 28, 19]])

#### 2-5-3 np.amin()
- np.amin(a, axis=None, out=None, keepdims=np.NoValue)

In [27]:
b = np.random.randint(30, size=(3, 5))
b

array([[11, 22, 11,  5, 10],
       [ 3, 26, 26,  7, 15],
       [19, 20, 24, 18,  4]])

In [28]:
# 所有元素裡最小值
np.amin(b)

3

In [29]:
# axis=0軸 3個3個比對挑最小的
np.amin(b, axis=0)

array([ 3, 20, 11,  5,  4])

In [30]:
# axis=1軸 5個5個比對挑最小的
np.amin(b, axis=1)

array([5, 3, 4])

### 2-6 取最大最小值的索引
- argmax()
- argmin()

#### 2-6-1 np.argmax()
- np.argmax(axis=None, out=None, keepdims=False)

In [2]:
a = np.random.randint(10, size=10)
a

array([4, 1, 1, 5, 8, 1, 1, 9, 3, 4])

In [3]:
# 回傳最大值的位置, 若有重複的, 則回傳第一次出現的位置
np.argmax(a)

7

In [4]:
# 也可以用method
a.argmax()

7

In [5]:
# 2-D
b = np.random.randint(10, size=(3, 4))
b

array([[6, 9, 3, 1],
       [3, 5, 9, 6],
       [7, 9, 1, 5]])

In [9]:
# 最大值9 第一次出現在索引1, 所以回傳 1
np.argmax(b)

1

In [7]:
# axis=0, 沿軸0, 取出三個元素比較, 回傳最大值的索引
np.argmax(b, axis=0)

array([2, 0, 1, 1], dtype=int64)

In [8]:
# axis=1, 沿軸1, 取出四個元素比較, 回傳最大值的索引
np.argmax(b, axis=1)

array([1, 2, 1], dtype=int64)

In [10]:
# 3-D
c = np.random.randint(10, size=(2, 3, 4))
c

array([[[6, 5, 4, 1],
        [6, 8, 6, 7],
        [4, 5, 8, 5]],

       [[7, 7, 2, 6],
        [4, 3, 7, 2],
        [0, 5, 1, 1]]])

In [11]:
# 不同軸的比較
np.argmax(c, axis=0)

array([[1, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0]], dtype=int64)

In [12]:
np.argmax(c, axis=1)

array([[0, 1, 2, 1],
       [0, 0, 1, 0]], dtype=int64)

In [13]:
np.argmax(c, axis=2)

array([[0, 1, 2],
       [0, 2, 1]], dtype=int64)

#### 2-6-2 np.argmin()
- np.argmin(axis=None, out=None, keepdims=False)
- 用法跟argmax一樣

In [15]:
b

array([[6, 9, 3, 1],
       [3, 5, 9, 6],
       [7, 9, 1, 5]])

In [14]:
np.argmin(b)

3

In [16]:
np.argmin(b, axis=0)

array([1, 1, 2, 0], dtype=int64)

In [17]:
np.argmin(b, axis=1)

array([3, 0, 2], dtype=int64)

### 2-7 陣列轉至
- np.transpose(a, axes=None)

In [18]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# 列變成行, 行變成列
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [23]:
# 預設的(0, 1)改成(1, 0)
np.transpose(a, axes=(1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [27]:
# 1d
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [28]:
np.transpose(b)

array([0, 1, 2, 3, 4, 5])

In [29]:
b.shape

(6,)

In [30]:
# 2d
b = b.reshape((1, 6))
b

array([[0, 1, 2, 3, 4, 5]])

In [31]:
np.transpose(b)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
c = np.arange(24).reshape(4, 3, 2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [34]:
d = np.transpose(c)
d

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [35]:
d.shape

(2, 3, 4)

In [36]:
# 用method
c.transpose()

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [40]:
# 也可以用 物件.T來轉置
c.T

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

### 2-8 陣列排序
- sort()
- argsort()

#### 2-8-1 np.sort() 與 np.argsort()
- 用法完全一樣
- np.sort(a, axis=-1, kind='quicksort', order=None)
- np.argsort(a, axis=-1, kind='quicksort', order=None)

In [41]:
a = np.random.randint(0, 100, size=20)
a

array([21,  0, 43, 33, 90, 59, 28, 97, 48, 40, 43, 40, 61, 64, 25, 97, 99,
       62, 73, 36])

In [42]:
# 回傳元素排序
np.sort(a)

array([ 0, 21, 25, 28, 33, 36, 40, 40, 43, 43, 48, 59, 61, 62, 64, 73, 90,
       97, 97, 99])

In [43]:
# 回傳index
np.argsort(a)

array([ 1,  0, 14,  6,  3, 19, 11,  9, 10,  2,  8,  5, 12, 17, 13, 18,  4,
        7, 15, 16], dtype=int64)

In [45]:
b = np.random.randint(0, 100, size=20).reshape(4, 5)
b

array([[81, 30,  5, 31, 60],
       [49, 16, 95, 98, 11],
       [63, 14,  9,  7, 41],
       [29, 58, 23, 76, 40]])

In [46]:
# 預設 axis=-1, 所以依照最後一軸來排序
np.sort(b)

array([[ 5, 30, 31, 60, 81],
       [11, 16, 49, 95, 98],
       [ 7,  9, 14, 41, 63],
       [23, 29, 40, 58, 76]])

In [47]:
np.argsort(b)

array([[2, 1, 3, 4, 0],
       [4, 1, 0, 2, 3],
       [3, 2, 1, 4, 0],
       [2, 0, 4, 1, 3]], dtype=int64)

In [48]:
np.sort(b, axis=0)

array([[29, 14,  5,  7, 11],
       [49, 16,  9, 31, 40],
       [63, 30, 23, 76, 41],
       [81, 58, 95, 98, 60]])

In [49]:
np.argsort(b, axis=0)

array([[3, 2, 0, 2, 1],
       [1, 1, 2, 0, 3],
       [2, 0, 3, 3, 2],
       [0, 3, 1, 1, 0]], dtype=int64)