In [1]:
import numpy as np

### 2-5 取最大最小值
- amax()
- amin()

#### 2-5-1 np.amax()
- np.amax(a, axis=None, out=None, keepdims=False)

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
# 回傳最大值
np.amax(a)

6

In [4]:
b = a.reshape(-1, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 回傳最大的那 row
np.amax(b, axis=0)

array([4, 5, 6])

In [6]:
# 回傳最大的那 col
np.amax(b, axis=1)

array([3, 6])

In [7]:
# 保留維度
np.amax(b, axis=1, keepdims=True)

array([[3],
       [6]])

#### 2-5-2 np.max()
- method

In [8]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[15, 14, 26, 27, 15],
        [12, 24, 25, 14, 12],
        [24,  2, 21,  4, 10]],

       [[16, 11,  1, 21,  3],
        [ 0, 10, 22, 28,  5],
        [19,  0,  9,  4, 14]]])

In [9]:
# 比較兩個陣列, 提出最大值
b.max(axis=0)

array([[16, 14, 26, 27, 15],
       [12, 24, 25, 28, 12],
       [24,  2, 21,  4, 14]])

In [10]:
# 兩個陣列每col最大值
b.max(axis=1)

array([[24, 24, 26, 27, 15],
       [19, 11, 22, 28, 14]])

In [13]:
# 兩個陣列每row最大值
b.max(axis=2)

array([[27, 25, 24],
       [21, 28, 19]])

#### 2-5-3 np.amin()
- np.amin(a, axis=None, out=None, keepdims=np.NoValue)

In [27]:
b = np.random.randint(30, size=(3, 5))
b

array([[11, 22, 11,  5, 10],
       [ 3, 26, 26,  7, 15],
       [19, 20, 24, 18,  4]])

In [28]:
# 所有元素裡最小值
np.amin(b)

3

In [29]:
# axis=0軸 3個3個比對挑最小的
np.amin(b, axis=0)

array([ 3, 20, 11,  5,  4])

In [30]:
# axis=1軸 5個5個比對挑最小的
np.amin(b, axis=1)

array([5, 3, 4])