In [1]:
import numpy as np

### 2-1 重塑
* reshape
* resize
    

#### 2-1-1 np.reshape() 
- np.reshape(a, newshape, order='C')

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = np.reshape(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
# 注意此時b 為淺拷貝
b[0, 1] = 0
a

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# order參數, 'C' 'F'
# C語言及 Fortran語言排列方式

c = np.arange(12)

In [6]:
# C: row major order
np.reshape(c, (3, 4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
# F: column major order
np.reshape(c, (3, 4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [8]:
# 也可以用 method的方式

In [9]:
d = np.arange(12)

In [10]:
# 寫法不同而已
d.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# 偷懶可以用 -1, 自動設定成合適的值
d.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 2-2-2 np.resize()
- np.resize(a, newshape)

In [12]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
# 大致上跟reshape相同
b = np.resize(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# 若超出, 不會報錯, 會從頭補
np.resize(a, (3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [15]:
# 若少於原本的, 也是從頭取
np.resize(a, (3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
# 另外, resize為深拷貝, 修改值不會引響原本的物件
b[0, 1] = 0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2-2 加入元素 append

#### 2-2-1 np.append()
* np.append(arr, values, axis)
    - arr: array like; 原始物件
    - values: array like; 要加入的
    - axis: int; 在哪一軸

In [17]:
# 不同軸元素新增方法

In [18]:
c = np.arange(12).reshape((3, 4))
d = np.linspace(0, 26, 12).reshape((3, 4))

In [19]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
d

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [21]:
# axis=None, return 1D-array
np.append(c, d)

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
       10.        , 11.        ,  0.        ,  2.36363636,  4.72727273,
        7.09090909,  9.45454545, 11.81818182, 14.18181818, 16.54545455,
       18.90909091, 21.27272727, 23.63636364, 26.        ])

In [22]:
# axis=0 return 2D, shape(3+3, 4)
np.append(c, d, axis=0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [23]:
# axis=1 return 2D, shape(3, 4+4)
np.append(c, d, axis=1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])

### 2-3 判斷真假 
- all() 
- any()

#### np.all()
- np.all(a, axis=None, out=None, keepdims=False)

In [30]:
a = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 0, 1],
])

In [31]:
# 全都是 0 以外才會回傳 True
np.all(a)

False

In [32]:
b = np.ones((3, 3))
np.all(b)

True

In [33]:
# 也可加入判斷式, 表示全部都小於2
np.all(b < 2) 

True

In [37]:
# 加入軸
np.all(a, axis=0)

array([ True, False,  True])

In [35]:
np.all(a, axis=1)

array([ True, False, False])

In [38]:
# keepdims, 維持原本的維度
np.all(a, axis=0, keepdims=True)

array([[ True, False,  True]])

In [39]:
# 也可以用 method
a.all()

False

In [40]:
(b < 3).all()

True

In [43]:
(b < 3).all(axis=1, keepdims=True)

array([[ True],
       [ True],
       [ True]])

#### np.any()
- np.any(a, axis=None, out=None, keepdims=False)

In [45]:
a = np.random.randint(10, size=(2, 3))
a

array([[1, 0, 9],
       [3, 9, 9]])