In [1]:
import numpy as np

## 2-9 陣列合併
* hstack
* vstack

### 2-9-1 np.hstack(tup)
* tup:含有陣列的tuple

In [36]:
a = np.arange(12)
b = np.arange(2)

In [37]:
np.hstack((a, b)) # 用tuple裝起來

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

In [38]:
# 1D 與 2D 合併會???
c = np.arange(4).reshape(2, 2)
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [39]:
# 2D array 合併
d = np.arange(6).reshape(2, 3)

In [40]:
c

array([[0, 1],
       [2, 3]])

In [41]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
np.hstack((c, d)) # d的元素直接接在c後面

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [43]:
np.arange(12).reshape(-1, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [44]:
e = np.arange(12).reshape(2, 2, 3)

In [45]:
f = np.arange(6).reshape(2, 1, 3)

In [46]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [47]:
f

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [48]:
# 3D 合併
# 要注意 hstack是對第一軸做合併, 
# 用"水平方向"處理來記會搞混
# 所以除了第一軸外其他軸的元素必須一樣
g = np.hstack((e, f))
g

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

In [49]:
print(e.shape)
print(f.shape)
print(g.shape) # 只有第一軸會增加

(2, 2, 3)
(2, 1, 3)
(2, 3, 3)


### 2-9-2 np.vstack(tup)
* tup:含有陣列的tuple

In [22]:
# 跟hstack用法一樣,
# 但要注意並不要用"垂直"的概念去理解
# 記得是對第0軸做處理就好
a = np.arange(12).reshape(-1, 1)
b = np.arange(2).reshape(-1, 1)

In [23]:
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [24]:
b

array([[0],
       [1]])

In [25]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [26]:
c = np.arange(2).reshape(1, 2)
d = np.arange(4).reshape(2, 2)

In [27]:
c

array([[0, 1]])

In [28]:
d

array([[0, 1],
       [2, 3]])

In [29]:
np.vstack((c, d))

array([[0, 1],
       [0, 1],
       [2, 3]])

In [30]:
e = np.arange(24).reshape(4, 3, 2)
f = np.arange(6).reshape(1, 3, 2)

In [31]:
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [32]:
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [34]:
g = np.vstack((e, f))
g

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [35]:
print(e.shape)
print(f.shape)
print(g.shape) # 只有第0軸的元素會增加

(4, 3, 2)
(1, 3, 2)
(5, 3, 2)


### 建立元素都是0的陣列
- np.zeros()
- np.zeros_like()

#### 2-10-1 np.zeros(shape, dtype=float, order='C')
深度學習做資料前處理時, 有時候需要將資料編碼成只有1個1, 其他均為0的形式,
這時候就可以使用此函數

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 2-10-2 np.zeros_like()
執行結果與 np.zeros一模一樣, 差異在不同使用情境<br>
如果已有一個陣列a, 想要見一個跟a形狀一樣但元素均為0的陣列時寫法會比較簡單<br>
以下範例說明:

In [53]:
a = np.arange(12).reshape(3, 4)

In [54]:
np.zeros(a.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 2-11 建立元素都是1的陣列
- ones()
- ones_like()

使用上跟 zeros差不多

#### 2-11-1 np.ones(shape, dtype, order='C')


In [56]:
np.ones(3)

array([1., 1., 1.])

In [57]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.ones(4, dtype=np.int8)

array([1, 1, 1, 1], dtype=int8)

#### 2-11-2 np.ones_like()

In [59]:
a = np.arange(12).reshape(3, 4)

In [61]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 2-12建立不限定員素質的陣列
- empty()

跟 zeros, ones類似, 但是不會賦予特定職所以產生速度快很多

#### 2-12-1 np.empty(shape, dtype=float, order='C')
這邊的empty不是"空", 事先規劃好陣列結構, 隨便填一個極小值做佔位而已


In [62]:
np.empty(5)

array([1.e-323, 2.e-323, 4.e-323, 4.e-323, 0.e+000])

In [65]:
np.empty((2, 3))

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [1.48539705e-313, 1.90979621e-313, 2.33419537e-313]])

速度比較

In [70]:
%%timeit
np.zeros(10000)

2.23 µs ± 6.44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [71]:
%%timeit
np.ones(10000)

2.87 µs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [72]:
%%timeit
np.empty(10000)

806 ns ± 3.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
