In [1]:
import numpy as np

### 2-21 陣列合併
- np.r_
- np.c_

#### 2-21-1 np.r_ 物件
#### 用法1: 合併
r 是指row(), 在基本的合併陣列用法上, 與np.vstack()相同

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
np.r_[a, b] # []填入欲合併的a b陣列, 並用逗號隔開

array([1, 2, 3, 4, 5, 6])

In [4]:
np.r_[5, a, 1.0] 

array([5., 1., 2., 3., 1.])

In [5]:
c = np.zeros((2, 3))
d = np.ones((3, 3))

In [6]:
np.r_[c, d] # shape: (2+3, 3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 用法2: 進階用法-設定控制字串
在 [ ] 的最前面加入控制字串<br>

`np.r['x, y, z', 陣列...]` <br>
'x, y, z'字串, 內含三個以逗號隔開的整數<br>
預設 '0, 0, -1' <br>
- x: 設定合併哪一軸(axis)
- y: 設定合併後的陣列至少要為幾軸
- z: 依y值的設定, 原始陣列可能需要增加軸數, z為增軸的方式



In [7]:
# x
a = np.ones((2, 2))
b = np.zeros((2, 2))

In [8]:
print(np.r_['1', a, b].shape)
np.r_['1', a, b]

(2, 4)


array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [9]:
print(np.r_['0', a, b].shape)
np.r_['0', a, b]

(4, 2)


array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [10]:
# 3D e.g.
a = np.ones((2, 2, 2))
b = np.zeros((2, 2, 2))

In [11]:
np.r_['0', a, b]

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
np.r_['1', a, b]

array([[[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.r_['2', a, b]

array([[[1., 1., 0., 0.],
        [1., 1., 0., 0.]],

       [[1., 1., 0., 0.],
        [1., 1., 0., 0.]]])

In [14]:
print(np.r_['0', a, b].shape)
print(np.r_['1', a, b].shape)
print(np.r_['2', a, b].shape)

(4, 2, 2)
(2, 4, 2)
(2, 2, 4)


In [15]:
# y (z預設-1)
# 1. y=2, 將原陣列 (3,) 增軸成 2D -> (1, 3)
# 2. 再依據 0軸合併 -> (2, 3)
np.r_['0, 2', [0, 1, 2], [3, 4, 5]].shape

(2, 3)

In [16]:
# z
# 1. y=2, 將原陣列 (3,) 增軸成 2D -> (1, 3)
# 2. z=0, 將原陣列元素移到第 0軸 -> (3, 1)
# 3. 再依據 0軸合併 -> (6, 1)
np.r_['0, 2, 0', [0, 1, 2], [3, 4, 5]].shape

(6, 1)

#### 用法3: 使用切片語法建立陣列
類似 `np.arange()` <br>
`np.r_[start: stop: step, 1D陣列...]`

In [17]:
np.r_[0: 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.r_[0: 10: 2]

array([0, 2, 4, 6, 8])

In [19]:
np.r_[10: 0: -1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
np.r_[0: 10, 0, 4, np.array([3, 2])] # 會全部合起來, 會傳1D陣列

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 2])

#### 用法4: 傳入'r', 'c' 字串建立矩陣物件
`np.r_['r'or'c', 陣列...]`
- 1D陣列的情況下, r則合併成row, c則合併成column

In [21]:
a = np.array([1, 4, 6])
b = np.array([3, 3, 3])

In [22]:
np.r_['r', a, b] # return 2d matrix

matrix([[1, 4, 6, 3, 3, 3]])

In [23]:
np.r_['c', a, b] # return 2d matrix

matrix([[1],
        [4],
        [6],
        [3],
        [3],
        [3]])

- 2d 設定'r', 'c'結果都一樣 <br>
實務上較少使用, 官方建議使用2D array取代矩陣做高速運算

In [24]:
c = np.ones((4, 5))
d = np.zeros((2, 5))

In [25]:
np.r_['r', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [26]:
np.r_['c', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

#### 2-12-2 np.c_物件
使用上跟np.r_差不多, np.c_預設是針對最後一軸做合併<br>
無論2D 3D 4D, 預設都是"最後"軸

In [27]:
a = np.ones((3, 2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
print(np.c_[a, b].shape)
np.c_[a, b]

(3, 5)


array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [30]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [31]:
np.c_[a, c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

### 2-22 陣列的儲存與讀取
- save()
- load()

#### 2-22-1 np.save() & np.load()

`np.save(file, arr, allow_pickle=True, fix_imports=True)`<br>
通常只有設定`file`及`arr`參數, 執行後會將陣列儲存成`.npy`格式的二進位檔

`np.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII)` <br>
讀取指定位置的`file`參數, 執行後回傳檔案內的陣列

`.npy`是特有格式, 無法相容於python以外的程式語言

In [33]:
a = np.random.randn(1200* 1000).reshape(1200, -1)

In [34]:
np.save('a', a) # 檔案名稱輸入完整的 'a.npy'也可以

In [37]:
b = np.load('a.npy')
b.shape

(1200, 1000)

### 2-23 以文字格式儲存, 讀取陣列內容
- savetxt()
- loadtxt()
- 與np.save(), np.load()相近, 支援常見的 txt, csv, dat等格式, 缺點是只能讀寫2d 陣列

#### 2-23-1 np.savetxt() & np.loadtxt()

`np.savetxt(fname, X, fmt, delimiter, newline, header, footer, comments, encoding)` <br>

`np.loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding)`

In [38]:
a = np.random.randn(3, 4)

In [39]:
np.savetxt('sample.txt', a)

In [40]:
b = np.loadtxt('sample.txt')

In [41]:
b

array([[ 0.64840804, -0.20401811, -0.63974576,  0.06680504],
       [-0.88969513, -0.70416665, -1.2251266 , -0.50591565],
       [ 0.94647599,  0.06705801,  1.2377948 ,  0.48513833]])

In [42]:
# 設定分割字元
np.savetxt('sample2.txt', a, delimiter=',')

In [44]:
# 讀檔也要設定!
try:
    np.loadtxt('sample2.txt')
except Exception as e:
    print(e)

could not convert string to float: '6.484080364456756840e-01,-2.040181086974559022e-01,-6.397457584318381185e-01,6.680503874422986932e-02'


In [45]:
np.loadtxt('sample2.txt', delimiter=',')

array([[ 0.64840804, -0.20401811, -0.63974576,  0.06680504],
       [-0.88969513, -0.70416665, -1.2251266 , -0.50591565],
       [ 0.94647599,  0.06705801,  1.2377948 ,  0.48513833]])

In [48]:
# 設定fmt
np.savetxt('sample3.txt', a, fmt='%.2f')

In [49]:
np.loadtxt('sample3.txt')

array([[ 0.65, -0.2 , -0.64,  0.07],
       [-0.89, -0.7 , -1.23, -0.51],
       [ 0.95,  0.07,  1.24,  0.49]])

### 2-24 建立隨機亂數的陣列
- random

#### 2-24-1
- np.random.rand(d0, d1, ..., dn): 0~1(不含1)的範圍內產生浮點數型別的亂數
- np.random.randint(low, high, size, dtype): 產生整數型別的亂數

In [50]:
np.random.rand()

0.8696231111362722

In [51]:
np.random.rand(2, 3)

array([[0.34904681, 0.58135117, 0.96254847],
       [0.80328851, 0.65011323, 0.41902532]])

In [57]:
# n~m的隨機浮點數
# (m-n) * np.random.rand() + m
(10 - 5) * np.random.rand(10) + 5

array([6.56329031, 6.30295007, 9.7819494 , 5.1424691 , 7.21692304,
       7.98895808, 9.36034973, 6.04707701, 7.59044589, 8.89597359])

In [54]:
np.random.randint(10)

3

In [55]:
np.random.randint(10, size=(2, 3))

array([[2, 6, 9],
       [4, 2, 9]])

In [56]:
np.random.randint(5, 10, size=(2, 3))

array([[9, 5, 7],
       [9, 6, 5]])

#### 2-24-2 np.random.seed()
- `np.random.seed(seed)`: 自訂種子

In [64]:
np.random.seed(21)

In [65]:
np.random.rand()

0.04872488080912729

In [66]:
np.random.seed(21)

In [67]:
np.random.rand()

0.04872488080912729

#### 2-24-3 np.random.choice()
- `np.random.choice(a, size, replace, p)`: 隨機抽元素

In [68]:
a = ['apple', 'banana', 'cat', 'dog', 'egg']

In [69]:
np.random.choice(a, 3) # 隨機抽三個

array(['apple', 'egg', 'apple'], dtype='<U6')

In [70]:
np.random.choice(a, 3, replace=False) # 隨機抽三個, 不重複抽樣

array(['banana', 'cat', 'dog'], dtype='<U6')

In [71]:
np.random.choice(a, 10, p=[0.8, 0.05, 0.05, 0.05, 0.05]) # 設定權重, 總和1

array(['apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'cat',
       'apple', 'apple', 'apple'], dtype='<U6')

In [73]:
np.random.choice(5, 10) # 傳入 a為整數5, 則與 np.arange(5)類似, 5為stop

array([2, 3, 0, 0, 3, 1, 4, 0, 2, 4])

#### 2-24-4 np.random.shuffle()
- `np.random.shuffle()`: 重新排列, 不會有回傳值

In [74]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.random.shuffle(a)

In [76]:
a

array([6, 4, 2, 1, 3, 7, 8, 5, 0, 9])