In [1]:
import numpy as np

### 2-13 建立指定範圍的等差陣列
- np.arange()

#### np.arange(start, stop, step, dtype=None)

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(-2) # 設定為負數時回傳空陣列

array([], dtype=int32)

In [4]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [5]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [6]:
np.arange(1.5, 6.5)

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [7]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.arange(10, 1, -1) #若遞增量為負, start > end

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [10]:
np.arange(1, 5, dtype='float64')

array([1., 2., 3., 4.])

In [17]:
# why???
np.arange(1, 5, 1.5, dtype='int')

array([1, 2, 3])

In [19]:
# cause int(1.5) -> 1
int(1.5)

1

### 2-14 建立指定範圍的等差陣列
- np.linspace()

#### 2-14-1 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- num:int 元素數量
- endpoint:boolean 是否包含stop
- retstep:boolean 是否顯示元素間的遞增量


留意endpoint, 預設是True, 即為包含stop<br>
該函數可以理解成 `start~top間, 切num-1`

In [20]:
a = np.linspace(0, 1)
print(a.shape)
a

(50,)


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

遞增量公式:<br> 
$\frac{(stop-start)}{(num-1)}$

In [21]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [26]:
np.linspace(0, 2, 3)

array([0., 1., 2.])

In [27]:
np.linspace(0, -2, 3) # stop可為負

array([ 0., -1., -2.])

In [28]:
np.linspace(0, 2, 3, endpoint=False) # 不包含stop
# 由於不包含stop, 遞增值計算方式為 (2-0) / 3

array([0.        , 0.66666667, 1.33333333])

In [31]:
b = np.linspace(0, 1, retstep=True)
b # 回傳 tuple, 遞增量在tuple最後的位置

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]),
 0.02040816326530612)

### 2-15 建立單位矩陣
- eye()
- identity()

#### 2-15-1 np.eye(N, M=None, k=0, dtype=float, order='C')
- 單位矩陣(Identity matrix; 數學用I表示); 函示名稱eye取i諧音, 避開常用變數i
- N:int 設定陣列列數
- M:int 設定陣列行數
- k:int 調整元素1這條對角線的位置, +往上偏移; -往下偏移

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(2, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [34]:
np.eye(8, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
np.eye(5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

另外np.eye可用於one hot encoding

In [39]:
tmp_list = [2, 5, 4, 1, 1, 2, 3]

In [40]:
# 將list內每個元素做one hot
np.eye(6)[tmp_list]

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

#### 2-15-2 np.identity(N, dtype=float)
- 陽春版的eye, 只能建立行列相同的矩陣且不能設定k

In [41]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

註:np.eye() & np.identity()速度比較其實沒有差太多

### 2-16 將陣列展平為1D陣列
- ndarray物件.flatten() <br>
留意他是 method, 回傳後是copy

In [43]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
b = a.flatten()

In [47]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
print(a.shape)
print(b.shape)

(2, 5)
(10,)


註: 其實可以用reshape達到一樣的效果, 但flatten不需設定參數, 名稱也很直覺