In [1]:
import numpy as np

#### 2-17 將陣列展平為1D
- ravel()

#### 2-17-1 np.ravel
- np.ravel(a, order='C')
- ndarray物件.ravel(order='C')


In [9]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`order='F'` :從最外面的軸讀取元素

In [12]:
a.ravel(order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

`order='A'` :以哪種方式存入記憶體就以哪種方式取出

In [13]:
a.ravel(order='A')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`order='K'` :一律依目前在記憶體的排序取出

In [14]:
a.ravel(order='K')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2-18找出不是0的元素
- nonzero()

#### 2-18-1 np.nonzero()
- np.nonzero()
- ndarry物件.nonzero()

In [16]:
a = np.random.randint(0, 10, size=30)
a

array([9, 6, 3, 5, 9, 1, 9, 6, 9, 5, 8, 7, 5, 2, 8, 6, 7, 6, 2, 0, 4, 8,
       7, 1, 8, 6, 6, 1, 6, 0])

In [17]:
np.nonzero(a) 

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),)

In [18]:
a.nonzero()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),)

In [19]:
a[a.nonzero()] # 選取非0的元素, 回傳陣列

array([9, 6, 3, 5, 9, 1, 9, 6, 9, 5, 8, 7, 5, 2, 8, 6, 7, 6, 2, 4, 8, 7,
       1, 8, 6, 6, 1, 6])

In [20]:
b = np.random.randint(0, 10, size=(4, 5))
b

array([[4, 7, 0, 5, 3],
       [0, 9, 7, 4, 5],
       [6, 0, 7, 7, 4],
       [9, 3, 1, 5, 5]])

In [21]:
b.nonzero() #會傳像是座標的概念

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 3, 4, 1, 2, 3, 4, 0, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [22]:
b[b.nonzero()] # 用索引取出來會展平為1D陣列

array([4, 7, 5, 3, 9, 7, 4, 5, 6, 7, 7, 4, 9, 3, 1, 5, 5])

### 2-19 複製陣列元素拼貼成新陣列
- tile()

#### 2-19-1 np.tile(a, reps)
- reps:int or 內含int的tuple, 此函式要熟悉的就是reps參數

In [23]:
a = np.array([1, 2, 3])

In [24]:
# 將傳入的陣列重複寫入兩次, 並銜接成一列
np.tile(a, 2) 

array([1, 2, 3, 1, 2, 3])

In [26]:
# reps為 (x, y)
# 則 axis 0複寫3次, axis 1複寫2次
np.tile(a, (3, 2)) 

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [27]:
# reps為 (x, y, z)
# axis0 * 2 ; axis1 * 3, axis2 * 4
np.tile(a, (2, 3, 4)) 

array([[[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]]])

### 2-20 增加陣列的軸數
- np.newaxis物件 

#### 2-20-1 以np.newaxis物件增加陣列軸數
##### 它是物件,不用()
`ndarray物件名稱[:, np.newaxis]`
有一些會用 `None`代替 `np.newaxis`, <br>
是因為`numpy`將`np.newaxis`定義為`None`<br>
這樣寫省事, 但`np.newaxis`好懂


np.newaxis 與 np.reshape()的差異<br>
主要是即便不知道原陣列個軸的維度時, 依然可以使用`np.newaxis`做增加軸的操作<br>
雖然 `np.reshape()`可以使用-1 來自動調整, 但只能使用在一個維度<br>
總結來說, 若只是想要單純增加陣列的軸數, 使用np.newaxis較為簡潔易懂

In [29]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a[np.newaxis, :, :] #多一個軸

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [31]:
a[np.newaxis, :, :].shape

(1, 3, 5)

In [32]:
a[:, np.newaxis, :] 

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [33]:
a[:, np.newaxis, :].shape

(3, 1, 5)

In [34]:
a[:, None, :] # 結果跟上面相同

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [35]:
a[:, None, :].shape

(3, 1, 5)