In [1]:
import numpy as np

#### 3-1-1 四則運算

In [2]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])

加法: + , np.add()

In [3]:
a + b

array([ 2,  5,  8, 11, 14])

In [4]:
a + 4

array([4, 5, 6, 7, 8])

In [5]:
np.add(a, b)

array([ 2,  5,  8, 11, 14])

In [6]:
np.add(a, 4) # 其實跟 + 一樣

array([4, 5, 6, 7, 8])

減法: -, np.subtract()

In [7]:
a - b

array([-2, -3, -4, -5, -6])

In [8]:
b - a

array([2, 3, 4, 5, 6])

In [9]:
a - 4

array([-4, -3, -2, -1,  0])

In [10]:
np.subtract(a, 4)

array([-4, -3, -2, -1,  0])

乘法: *, np.multiply()

In [11]:
a * b

array([ 0,  4, 12, 24, 40])

In [12]:
a * 2

array([0, 2, 4, 6, 8])

In [13]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

除法: /, np.divide() <br>
餘數: %, np.mod()


In [14]:
a / b

array([0.        , 0.25      , 0.33333333, 0.375     , 0.4       ])

In [15]:
np.divide(a, b)

array([0.        , 0.25      , 0.33333333, 0.375     , 0.4       ])

In [16]:
a % 2

array([0, 1, 0, 1, 0], dtype=int32)

In [17]:
np.mod(a, 2)

array([0, 1, 0, 1, 0], dtype=int32)

In [23]:
b // 3 # 個元素除3後求商

array([0, 1, 2, 2, 3], dtype=int32)